### ISSUE TITLE
Add initial UI of the application.

### ISSUE THREAD

**Issue by siddharth952** [fossasia/badge-magic-ios#10]
To implement UI similar to the android version of the app, while following the apple design guidelines.

![](https://raw.githubusercontent.com/fossasia/badge-magic-android/development/docs/images/screen-1.png)

**Comment by adityastic** [comment]
Let's get something basic setup for a moment

**Comment by adityastic** [comment]
The core implementation with a textfield and a button should be enough for the start

**Comment by kushthedude** [comment]
How you guys are planning for badgemagic Ios and also what have you come up with for the initial start?

**Comment by adityastic** [comment]
@kushthedude our initial plan atm is to get the core functionality working i.e. using ble to program the badge.
